name: build

on:
  workflow_dispatch:

jobs:
  push-to-ibm-foundry:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Web
        run: |
          git clone https://github.com/gamekingv/docker-drive.git
          cd docker-drive
      #     yarn
      #     yarn build
      #     mv ./extension/dist ../server/views
      
      - name: Set Repository
        run: |
          ls
          echo '{"url":"${{ secrets.URL }}","account":"${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}"}' > ./server/repository.json

      # - name: Install IBM Cloud CLI
      #   run: |
      #     curl -o cli.tar.gz https://clis.cloud.ibm.com/download/bluemix-cli/latest/linux64
      #     tar -xzvf cli.tar.gz
      #     chmod -R 777 ./Bluemix_CLI/
      #     cd Bluemix_CLI
      #     ./install
      #     cd ../server
          
      # - name: Login IBM Cloud
      #   env:
      #     IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
      #   run: |
      #     ibmcloud login <<EOF
      #     $IBM_ACCOUNT
      #     7
      #     no
      #     EOF

      # - name: Target IBM Cloud
      #   run: |
      #     ibmcloud target --cf
      #     ibmcloud cf install -f

      # - name: Restart IBM Cloud
      #   run: |
      #     ibmcloud cf push
