name: build

on:
  workflow_dispatch:

jobs:
  push-to-ibm-foundry:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Web
        run: |
          git clone https://github.com/gamekingv/docker-drive.git
          cd docker-drive
          echo '{"buildAsExtension": false}' > ./src/build-type.json
          yarn
          yarn build
          cd ..
          mv ./docker-drive/extension/dist ./views
          rm -rf docker-drive
      
      - name: Set Repository
        run: echo '{"url":"${{ secrets.URL }}","account":"${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}"}' > ./repository.json

      - name: Install IBM Cloud CLI
        run: |
          curl -o cli.tar.gz -L https://clis.cloud.ibm.com/download/bluemix-cli/latest/linux64
          tar -xzvf cli.tar.gz
          rm -f cli.tar.gz
          chmod -R 777 ./Bluemix_CLI/
          cd Bluemix_CLI
          ./install
          cd ..
          rm -rf Bluemix_CLI
          
      - name: Login IBM Cloud
        env:
          IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
        run: |
          ibmcloud login <<EOF
          $IBM_ACCOUNT
          9
          no
          EOF

      - name: Target IBM Cloud Foundry
        run: |
          ibmcloud target --cf
          ibmcloud cf install -f

      - name: Push to IBM Cloud
        run: |
          ibmcloud cf push
